name: cringe
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: classes
